<a href="https://colab.research.google.com/github/markapurammarthanda12/Python_Notes/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating Numpy Array



In [3]:
import numpy as np

In [3]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [19]:
# b=np.array([10,20,30],dtype='bool')
b=np.array([10,20,30],dtype='float')
b

array([10., 20., 30.])

In [11]:
#2d arr
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
#3d arr
c=np.array([
    [[1,2,3],[4,5,6]],
     [[7,8,9],[10,11,12]]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [15]:
c.shape

(2, 2, 3)

In [20]:
# arange = range()
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
a=np.arange(1,13).reshape(2,2,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
np.ones((3,4),dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [35]:
a.size

12

In [36]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
np.random.random((3,4))*100

array([[34.63767088, 29.16672729, 79.78230983, 13.03521178],
       [98.41500685, 48.84872297, 60.60939193, 60.90408762],
       [63.95668341, 81.47021022, 50.19973475, 21.50281379]])

In [49]:
np.linspace(-10,10,10,dtype='int')

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [51]:
np.identity(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# **Array Attributes**

In [4]:
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype='float').reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [56]:
a3.ndim

3

In [60]:
a3.shape

(2, 2, 2)

In [64]:
a1.size

10

In [71]:
a3.itemsize


8

In [73]:
a3.dtype

dtype('int64')

In [77]:
m=a3.max()
print(m)

7


In [6]:
a3.astype('int32')

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# **Array Operations**

In [19]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
#scalar operations
#arithmetic
a1
a1*2
a1**2
a1/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [24]:
#relational
a1*3>=a2
a1>a2
a1==a2
a1>5
a1<=4

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [26]:
#vector operations
#arithmetic
a1+a2 #shape should be same

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# **Array Functions**

In [36]:
a1=np.random.random((3,3))*100
a1=np.round(a1)
a1

array([[19., 58., 20.],
       [59., 99., 46.],
       [98., 27., 14.]])

In [44]:
np.max(a1,axis=0) #axis-0 for 'col' wise
np.max(a1,axis=1) #axis-1 for 'row' wise
np.sum(a1)#min,max,sum,prod

np.float64(440.0)

In [46]:
print(np.mean(a1)) #mean,median,std,var
print(np.median(a1,axis=0))
print(np.std(a1))
print(np.var(a1))

48.888888888888886
[59. 58. 20.]
30.80564322199729
948.9876543209876


In [47]:
#dot product
np.dot(a1,a2)

array([[1556., 1653., 1750., 1847.],
       [3212., 3416., 3620., 3824.],
       [1888., 2027., 2166., 2305.]])

In [49]:
#log and epxonents
np.log(a1)
np.exp(a1)

array([[1.78482301e+08, 1.54553894e+25, 4.85165195e+08],
       [4.20121040e+25, 9.88903032e+42, 9.49611942e+19],
       [3.63797095e+42, 5.32048241e+11, 1.20260428e+06]])

In [51]:
#round,floor,ceil
np.round(np.random.random((2,3))*100)

array([[56., 99., 38.],
       [25., 84., 62.]])

In [52]:
#trigonometric funs
np.sin(a1)

array([[ 0.14987721,  0.99287265,  0.91294525],
       [ 0.63673801, -0.99920683,  0.90178835],
       [-0.57338187,  0.95637593,  0.99060736]])

# **Indexing and Slicing**

In [53]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)


In [60]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [59]:
a2[2,3] # [row col]

np.int64(11)

In [63]:
a3[1,1,0]

np.int64(6)

In [64]:
# lets start slicing
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a1[2:5:2]

array([2, 4])

In [66]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
a2[:,2]
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [83]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [88]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# **Iterating**

In [89]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [92]:
for i in a1: # each time print one element
  print(i)

0
1
2
3
4
5
6
7
8
9


In [93]:
for i in a2: #each time print one row
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [94]:
for i in a3: #each time print a 2d arr
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [96]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# **Reshaping**

In [100]:
#reshape,transpose,ravel
np.transpose(a2)
a2.T


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [109]:
np.ravel(a2)
#or
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# **Stacking**

In [110]:
#horizontal,vertical stacking
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [111]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [113]:
np.vstack((a5,a4))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# **Splitting**

In [114]:
#horizontal,vertical splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [119]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [120]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]